version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build: ./backend/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    ports:
      - 3001:3000
    depends_on:
      - db
  front:
      build: ./frontend/
      volumes:
        - ./frontend/app:/front
      ports:
        - 3000:3000
      tty: true
      stdin_open: true
      environment:
        - CHOKIDAR_USEPOLLING=true
volumes:
  data-volume: