# Workflowの名前。任意に設定可能
name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
   branches:
     - main
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
     - name: Deploy
       with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd EnglishSpeak
            git pull origin main
         
