name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
   branches:
     - main
 
#実行される処理
jobs:
 build:
   # 実行環境の指定
   runs-on: ubuntu-latest
   steps:

     # デプロイする
      - name: Deploy
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh  ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -i private_key "cd EnglishSpeak && git pull origin main"
