name: EC2 auto deploy

# アクションが実行されるタイミングを設定。今回はmainブランチにpushされた時。
on:
 push:
   branches:
     - main
 
#実行される処理
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no private_key ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:~/.ssh/id_rsa
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}
        shell: bash

      - name: Deploy code
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} "cd EnglishSpeak && git pull origin main"
